// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuh8q2m0mhZuJuHBRaQrKJ0snE8Svj0Uw',
    appId: '1:546879107116:android:699409d481a48127116189',
    messagingSenderId: '546879107116',
    projectId: 'lamber-capstone',
    databaseURL: 'https://lamber-capstone-default-rtdb.firebaseio.com',
    storageBucket: 'lamber-capstone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcD7n_EjOCA6w18FdWjp-XeEZinClXfyc',
    appId: '1:546879107116:ios:4b8c8c82e21e059c116189',
    messagingSenderId: '546879107116',
    projectId: 'lamber-capstone',
    databaseURL: 'https://lamber-capstone-default-rtdb.firebaseio.com',
    storageBucket: 'lamber-capstone.appspot.com',
    iosClientId: '546879107116-midfq7dii83mh8d81hin8rl7m16rdjr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.lamber',
  );
}
